### ISSUE TITLE
Production API Requires HTTPS

### ISSUE THREAD

**Issue by Kexerval** [neit-kite/kite#1]
Chrome will not allow mixed content `fetch()` calls to be made on secure site origins. Eg: an HTTP request on HTTPS. The API must have a TLS certificate, that doesn't necessarily needs to be trusted by the client's operating system at this time.

**Comment by RetWolf** [comment]
I will be looking into this today(11/7), and tomorrow(11/8). If we cannot come to an easy solution, we should discuss workarounds in the meantime.

**Comment by RetWolf** [comment]
Ian when you get a chance look at how HTTPS actually works. Technically you are in charge of the API so this issue should fall on your shoulders.

**Comment by ianfabs** [comment]
School work comes first, so once i catch up, yeah

**Comment by Kexerval** [comment]
Live as of 11/8
