### ISSUE TITLE
/api/docker does not return available containers

### ISSUE THREAD

**Issue by Kexerval** [neit-kite/kite#6]
Expected output:

- Show a list of all available containers

Current output:

- 404 with container not available

**Comment by ianfabs** [comment]
Fixed in commit 8fc7035ab8b9e21cdb92486d8d29556beb4b6042
Commited the /api/docker route

**Comment by Kexerval** [comment]
May want to take another look, when making a GET request to /api/docker @RetWolf said I was requesting an undefined value

**Comment by ArowShot** [comment]
Fixed in e1ca5165581cef498b9964e16019c27d455b48e9, I guess reverting an old merge casued the fix for this bug to not be present in the linux branch.
